### What is Numpy?
- NumPy is the fundamental package for scientific computing in Python
- It is a Python library that provides a multidimensional array object, various derived objects
(such as masked arrays and matrices)
- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional
arrays of homogeneous data types


In [5]:
# Creating numpy array 
import numpy as np 
np.array([1,2,3,4,555,65,70]) # 1 D array
arr=np.array([1,2,3,4,555,65,70]) # vector
print(arr)

## 2 D array (marrix)
arr=np.array([[12,23,45,56],[12,34,56,78]]) ### the shape should be same 
print(arr)

[  1   2   3   4 555  65  70]
[[12 23 45 56]
 [12 34 56 78]]


### dtype
- The desired data-type for the array. If not given, then the type willbe determined as the
minimum type required to hold the objects in thesequence

In [11]:
arr=np.array([12,23,34,56,60], dtype=float)
print(arr)

arr=np.array([12,23,34,56,60], dtype=int)
print(arr)

arr=np.array([12,23,34,56,60], dtype=str)
print(arr)

arr=np.array([12,23,34,56,0], dtype=bool) # if non sero value in array , it will give True else it will give False
print(arr)

arr=np.array([12,23,34,56,60], dtype=complex)
print(arr)


[12. 23. 34. 56. 60.]
[12 23 34 56 60]
['12' '23' '34' '56' '60']
[ True  True  True  True False]
[12.+0.j 23.+0.j 34.+0.j 56.+0.j 60.+0.j]


#### Numpy Arrays Vs Python Sequences
- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically).
- Changing the size of an ndarray will create a new array and delete the original.
- The elements in a NumPy array are all required to be of the same data type, and thus will be
the same size in memory.
- NumPy arrays facilitate advanced mathematical and other types of operations on large
numbers of data. Typically, such operations are executed more efficiently and with less code
than is possible using Python’s built-in sequences

### arange
- arange can be called with a varying number of positional arguments

In [13]:
arr=np.arange(1, 25) # 1 include 25th is exclude , it will print the sequence till 24 
print(arr)

arr=np.arange(1,25,2) ## lower upper and step
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 1  3  5  7  9 11 13 15 17 19 21 23]


### reshape
- Both of number products should be equal to umber of Items present inside the array.

In [18]:
arr=np.arange(1,13).reshape(6,2) ### 6rows and 2 columns 
print(arr)

arr=np.arange(1,13).reshape(3,4) ## 3 rows and 4 columns
print(arr)

arr=np.arange(1,13).reshape(4,3) ## 4 rows and 3 columns
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### ones & Zeros
- you can initialize the values and create values . ex: in deep learning weight shape

In [24]:
arr=np.ones((3,4)) # mentioned inside tuple 
print(arr)

arr=np.zeros((3,4)) # mentioned inside tuple 
print(arr)

arr=np.ones((3,4),dtype=int) # mentioned inside tuple 
print(arr)

arr=np.zeros((3,4),dtype=int) # mentioned inside tuple 
print(arr)

arr=np.ones((3,4),dtype=str) # mentioned inside tuple 
print(arr)

arr=np.zeros((3,4),dtype=str) # mentioned inside tuple 
print(arr)

arr=np.ones((3,4),dtype=complex) # mentioned inside tuple 
print(arr)

arr=np.zeros((3,4),dtype=complex) # mentioned inside tuple 
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [32]:
# Another Type ---> random()

arr=np.random.random((3,4))
print(arr)

arr=np.random.randint((3,4))
print(arr)

arr=np.random.randn(2,4)
print(arr)

arr=np.random.random_integers(2,4)
print(arr)

[[0.25584594 0.59738409 0.48652995 0.33272104]
 [0.25667487 0.31992479 0.71933143 0.50988131]
 [0.8313525  0.56250373 0.20765155 0.54759417]]
[0 1]
[[-1.7544763  -0.05069207  0.65508088 -0.45061261]
 [ 0.30168512 -0.86642608  0.74867159  1.2362263 ]]
2


C:\Users\Home\AppData\Local\Temp\ipykernel_10512\1266484363.py:12: DeprecationWarning: This function is deprecated. Please call randint(2, 4 + 1) instead
  arr=np.random.random_integers(2,4)


### linspace
- It is also called as Linearly space , Linearly separable,in a given range at equal distance it
creates points.

In [37]:
arr=np.linspace(-10,10,50) # lower ,upper ,number element to  generate, especially used for to generate the points
print(arr)

arr=np.linspace(-10,10,50,dtype=int) # lower ,upper ,number element to  generate, especially used for to generate the points
print(arr)

arr=np.linspace(-10,10,50,dtype=float) # lower ,upper ,number element to  generate, especially used for to generate the points
print(arr)

arr=np.linspace(-10,10,50,dtype=str) # lower ,upper ,number element to  generate, especially used for to generate the points
print(arr)

arr=np.linspace(-10,10,50,dtype=complex) # lower ,upper ,number element to  generate, especially used for to generate the points
print(arr)

[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]
[-10 -10 -10  -9  -9  -8  -8  -8  -7  -7  -6  -6  -6  -5  -5  -4  -4  -4
  -3  -3  -2  -2  -2  -1  -1   0   0   1   1   1   2   2   3   3   3   4
   4   5   5   5   6   6   7   7   7   8   8   9   9  10]
[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -

### identity
- indentity matrix is that diagonal items will be ones and evrything will be zeros

In [39]:
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Array Attributes

In [43]:
arr=np.arange(10)
print(arr)

arr=arr.reshape(5,2)
print(arr)

arr=np.arange(12, dtype=float).reshape(3,4) ## metrix 
print(arr)

arr=np.arange(8 ,dtype=float).reshape(2,2,2) ## tesnor 3 d array
print(arr)




[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


In [ ]:
# ndim : To findout given arrays number of dimensions

print(arr.ndim)
 ## shape , given number of dimentions 
print(arr.shape)

print(arr.size) ## given number of item in array

print(arr.itemsize) ### memory occupied by the items, # integer 64 gives = 8 bytes

print(arr.dtype) # given data type of items

arr=arr.astype(int) ## changin data type of item
print(arr.dtype)

3
(2, 2, 2)
8
8
float64
int64


### Array operations

In [53]:
arr1=np.arange(12).reshape(3,4)
arr2=np.arange(12,24).reshape(3,4)
print(arr1)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### scalar operations
- Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication
on each element of a Numpy array.

In [55]:
print(arr1+2)
print(arr1-2)
print(arr1*2)
print(arr1/2)
print(arr1%2)
print(arr1//2)
print(arr1**2)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


### relational Operators
- The relational operators are also known as comparison operators, their main function is to
return either a true or false based on the value of operands

In [ ]:
print(arr1>2) ### any value prenset in side ndarray is greater than 2 it will give  true else flase


[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### Vector Operation
- We can apply on both numpy array

In [ ]:
# arithmetic operation, operatiosn will on repective index location
print(arr1+arr2)
print(arr1-arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1*arr2)
print(arr1**arr2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


### Array functions

In [59]:
arr1=np.random.random((3,3))
print(arr1)

[[0.39672226 0.12821952 0.90114171]
 [0.76990091 0.64322956 0.39159896]
 [0.28059391 0.91002176 0.62041065]]


In [60]:
arr1=np.round(arr1*100)
print(arr1)

[[40. 13. 90.]
 [77. 64. 39.]
 [28. 91. 62.]]


In [63]:
print(np.min(arr1)) # it will minimum value from array
print(np.max(arr1)) # it will give max value from arr1 array
print(np.sum(arr1)) # it will add all elements of array and return the sum of
print(np.prod(arr1)) ## it will multiply off all elemets an return the that




13.0
91.0
504.0
1420928654745600.0


### In numpy 
- 0==Column , 1== row

In [ ]:
# operations row wise 
print(np.max(arr1,axis=1)) ## it will give max value from each row in array 
print(np.min(arr1,axis=1)) ## it will give min value from each row in array
print(np.sum(arr1,axis=1))## it will add element row wise and return the eaxh row sum
print(np.prod(arr1,axis=1))## it will multiply of each row elemnt an return the each element row multiplication



[90. 77. 91.]
[13. 39. 28.]
[143. 180. 181.]
[ 46800. 192192. 157976.]


In [65]:
# operations columns wise 
print(np.max(arr1,axis=0)) ## it will give max value from each column in array 
print(np.min(arr1,axis=0)) ## it will give min value from each column in array
print(np.sum(arr1,axis=0))## it will add element columns wise and return the eaxh columns sum
print(np.prod(arr1,axis=0))## it will multiply of each column elemnt an return the each element columns multiplication



[77. 91. 90.]
[28. 13. 39.]
[145. 168. 191.]
[ 86240.  75712. 217620.]


### Statistics related fuctions

In [78]:
print(arr1.mean()) ## it will return mean of array 
print(arr1.mean(axis=0)) # it will return mean of each column
print(arr1.mean(axis=1))# it will return mean of each row 
print(np.median(arr1)) ## it will return meadian of array 
print(np.mean(arr1)) ## it will return mean of array
print(np.mean(arr1,axis=1)) ## it will return mean row wise 
print(np.mean(arr1,axis=0)) ## it will return mean column wise
print(np.median(arr1,axis=1)) ## it will return median row wise 
print(np.median(arr1,axis=0)) ## it will return median column wise 

print(arr1.std()) ## it will return standarad vediation 
print(arr1.std(axis=1)) # it will print standard deviation row wise 
print(arr1.std(axis=0)) # it will retun std column wise 

print(np.std(arr1)) # it will retunr standard deviation of metrix 
print(np.std(arr1,axis=1)) # it will return standard deviation row wise 
print(np.std(arr1,axis=0)) # it will return standarad deviation column wise 

print(arr1.var()) # it will return varaince of array metrix 
print(arr1.var(axis=1)) # it will print varaince row wise 
print(arr1.var(axis=0)) # it will print variance column wise 

print(np.var(arr1)) # it will return varaince of array metrix 
print(np.var(arr1,axis=1))# it will return varaince row wise 
print(np.var(arr1, axis =0)) # it will print variance column wise 


 


56.0
[48.33333333 56.         63.66666667]
[47.66666667 60.         60.33333333]
62.0
56.0
[47.66666667 60.         60.33333333]
[48.33333333 56.         63.66666667]
[40. 64. 62.]
[40. 64. 62.]
26.034165586355517
[31.89914663 15.76916823 25.74662869]
[20.85398976 32.34192326 20.85398976]
26.034165586355517
[31.89914663 15.76916823 25.74662869]
[20.85398976 32.34192326 20.85398976]
677.7777777777778
[1017.55555556  248.66666667  662.88888889]
[ 434.88888889 1046.          434.88888889]
677.7777777777778
[1017.55555556  248.66666667  662.88888889]
[ 434.88888889 1046.          434.88888889]


### Trignometry Functions

In [81]:
print(np.sin(arr1)) ## it will return sin values of each element 
print(np.cos(arr1)) ## it return cos values of each element 
print(np.tan(arr1)) ## it return tan values of each element 

[[ 0.74511316  0.42016704  0.89399666]
 [ 0.99952016  0.92002604  0.96379539]
 [ 0.27090579  0.10598751 -0.7391807 ]]
[[-0.66693806  0.90744678 -0.44807362]
 [-0.03097503  0.39185723  0.26664293]
 [-0.96260587 -0.99436746  0.67350716]]
[[ -1.11721493   0.46302113  -1.99520041]
 [-32.26857578   2.34786031   3.61455441]
 [ -0.2814296   -0.10658787  -1.09750978]]


### dot product
- The numpy module of Python provides a function to perform the dot product of two arrays

In [83]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(4,3)

print(np.dot(arr1,arr2))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


### Log and Exponents

In [88]:
print(np.log(arr1))




[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]


C:\Users\Home\AppData\Local\Temp\ipykernel_10512\3191482829.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr1))


In [86]:
print(np.exp(arr1))
print(np.exp2(arr1))

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]
[[1.000e+00 2.000e+00 4.000e+00 8.000e+00]
 [1.600e+01 3.200e+01 6.400e+01 1.280e+02]
 [2.560e+02 5.120e+02 1.024e+03 2.048e+03]]


round / floor /ceil

### round
- The numpy.round() function rounds the elements of an array to the nearest integer or to the
specified number of decimals.

In [91]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
print(np.round(arr)) ## it will return value in round figure 
print(np.ceil(arr)) ## it will return the max  malue in round 
print(np.floor(arr)) ## it will floor value 

[1. 3. 4. 5.]
[2. 3. 4. 5.]
[1. 2. 3. 4.]


In [92]:
arr1 = np.arange(10)
arr2= np.arange(12).reshape(3,4)
arr3 = np.arange(8).reshape(2,2,2)

### Indexcing on 1 D array

In [ ]:
# indexcing on 1 D array
print(arr1)
print(arr1[1]) # it will return 1ts index element 
print(arr1[-1]) # it will return last element from array 
print(arr1[3])
print(arr1[-3]) ## it will return 3rd element from last 



[0 1 2 3 4 5 6 7 8 9]
1
9
3
7


### Indexing on 2 D array 

In [ ]:
print(arr2)
### fetching desire output 6 from array
print(arr2[1,2]) # row and column strt from zero
### fetching desire output 3 from array
print(arr2[0,3])

### fetching desire output 11 from array
print(arr2[2,3])

### fetching desire output 5 from array
print(arr2[1,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
3
11
5


### indexing on 3D ( Tensors)


In [108]:
print(arr3)
## print desire output 3 
print(arr3[0,1,1])

## print desire output 7
print(arr3[1,1,1])

# print desire ouptu 5
print(arr3[1,0,1])


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
7
5


### Slicing
Fetching Multiple items

In [ ]:
print(arr1)
## fetching desire output 3,4 ,5
print(arr1[3:6])  #6th index  is exclued 
print(arr1[2:8])  # 8th index is exclued


[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[2 3 4 5 6 7]


### Slicing on 2D

In [ ]:
print(arr2)
print(arr2[0,:]) ## fetching first row
print(arr2[:,2]) ## fectchin 3rd column

## fectchin 5,6 and 9,10
print(arr2[1:3]) ## for rows
print(arr2[1:3,1:3])

print(arr2[::2,::3])

# EXPLANATION : Here we take (:) because we want all rows , second(:2) for alternate value,
# and (:) for all columns and (:3) jump for two steps


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]


In [ ]:
arr2[::2 ,1::2] # columns , arr2[::2] for alternate rows

array([[ 1,  3],
       [ 9, 11]])

In [124]:
# slicing on 3 D array
arr3[0::2 , 0 , ::2] # for columns


array([[0]])

### iterating

In [125]:
for i in arr1:
    print(i)

for i in arr2:
    print(i)
    
for i in arr3:
    print(i)

0
1
2
3
4
5
6
7
8
9
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
# using nditer
for i in np.nditer(arr3): # first it will convert into 1  d array
    print(i)

0
1
2
3
4
5
6
7


### Ravle 
- convert any dimentions array to 1 d Array



In [127]:
print(np.ravel(arr2))
print(np.ravel(arr3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7]


### Stacking
- Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be
stacked

In [130]:
# Horizontal stacking
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(3,4)

np.hstack((arr1,arr2))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [131]:
# vertical stacking
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(3,4)

np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting
- its opposite of Stacking

In [137]:
# horizontal splitting 
np.hsplit(arr1,2) ## split into tow array



[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [138]:
## vertical splitting 
np.vsplit(arr1,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

### Numpy Arrays Vs Python Sequences
- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically).
Changing the size of an ndarray will create a new array and delete the original
- The elements in a NumPy array are all required to be of the same data type, and thus will be
the same size in memory
- NumPy arrays facilitate advanced mathematical and other types of operations on large
numbers of data. Typically, such operations are executed more efficiently and with less code
than is possible using Python’s built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy
arrays; though these typically support Python-sequence input, they convert such input to
NumPy arrays prior to processing, and they often output NumPy arrays

In [140]:
# Element-wise addition
a = [ i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

6.164193630218506


In [145]:
a=[i for i in range (10000000)]
a=[i for i in range (10000000,20000000)]

import time 

start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])

print(time.time()-start)




5.992578983306885


In [146]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)

start=time.time()
c=a+b
print(time.time()-start)

0.6883406639099121


In [148]:
5.992578983306885 / 0.6883406639099121
## so ,Numpy is Faster than Normal Python programming ,we can see in above Example. because Numpy uses C type array

8.705833168808947

In [ ]:
list1=[i for i in range(10000000)]
import sys 
sys.getsizeof(list1)

89095160

In [150]:
arr=np.arange(10000000)
sys.getsizeof(arr)

80000112

In [153]:
# we can decrease more in numpy
arr=np.arange(10000000,dtype=np.int32)
sys.getsizeof(arr)

40000112

In [154]:
# we can decrease more in numpy
arr=np.arange(10000000,dtype=np.int16)
sys.getsizeof(arr)

20000112

### Advance Indexing and Slicing

In [155]:
# Normal Indexing and slicing
arr= np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [157]:
# fetching 5 from array
arr[1,2]

np.int64(5)

In [159]:
## fetching 4,5,7,8 from array
arr[1:3 , 1:3]

array([[4, 5],
       [7, 8]])

### Fancy Indexing
- Fancy indexing allows you to select or modify specific elements based on complex conditions
or combinations of indices. It provides a powerful way to manipulate array data in NumPy.

In [161]:
# Fetch 1,3,4 row
arr[[1,2,3]]

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [162]:
# New array
z = np.arange(24).reshape(6,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [163]:
# Fetch 1, 3, ,4, 6 rows
z[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [164]:
# Fetch 1,3,4 columns
z[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

### Boolean indexing
It allows you to select elements from an array based on a Boolean condition. This allows you
to extract only the elements of an array that meet a certain condition, making it easy to perform
operations on specific subsets of data

In [166]:
G = np.random.randint(1,100,24).reshape(6,4)
G>50

array([[False,  True, False, False],
       [False, False,  True,  True],
       [ True,  True, False, False],
       [ True, False, False, False],
       [ True, False, False,  True],
       [ True, False,  True, False]])

In [ ]:
G[G>50] ## # Where is True , it gives result , everything other that removed.we got values

array([92, 75, 69, 92, 66, 57, 54, 59, 77, 78], dtype=int32)

In [168]:
# find out even numbers
G % 2 == 0

array([[False,  True, False, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True, False, False],
       [False,  True,  True,  True]])

In [169]:
G[G% 2 == 0]

array([92, 44, 10, 92, 66, 14,  6, 16, 26, 54,  6,  4, 78,  6],
      dtype=int32)

In [170]:
# find all numbers greater than 50 and are even
(G > 50 ) & (G % 2 == 0)

array([[False,  True, False, False],
       [False, False, False, False],
       [ True,  True, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False,  True, False]])

In [171]:
G[(G > 50 ) & (G % 2 == 0)]# find all numbers greater than 50 and are even


array([92, 92, 66, 54, 78], dtype=int32)

In [172]:
# Result
G[~(G % 7 == 0)] # (~) = Not

array([92, 31, 19, 44, 10, 75, 69, 92, 66,  6, 57, 16, 26, 15, 54,  6, 31,
       59,  4, 78,  6], dtype=int32)

### Broadcasting
- Used in Vectorization
- The term broadcasting describes how NumPy treats arrays with different shapes during
arithmetic operations.
-The smaller array is “broadcast” across the larger array so that they have compatible shapes

In [2]:
import numpy as np 
# same shape
arr1=np.arange(6).reshape(2,3)
arr2=np.arange(6,12).reshape(2,3)

print(arr1)
print(arr2)

print(arr1+arr2)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [4]:
## different shape 
arr1=np.arange(6).reshape(2,3)
arr2=np.arange(3).reshape(1,3)

print(arr1)
print(arr2)

print(arr1+arr2)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


### Broadcasting Rules
1. Make the two arrays have the same number of dimensions.
If the numbers of dimensions of the two arrays are different, add new dimensions with size
1 to the head of the array with the smaller dimension.
ex : (3,2) = 2D , (3) =1D ---> Convert into (1,3)
(3,3,3) = 3D ,(3) = 1D ---> Convert into (1,1,3)
2. Make each dimension of the two arrays the same size.
If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are
stretched to the size of the other array.
ex : (3,3)=2D ,(3) =1D ---> CONVERTED (1,3) than strech to (3,3)
If there is a dimension whose size is not 1 in either of the two arrays, it cannot be
broadcasted, and an error is raised.

In [ ]:
# More examples
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a+b) # Arthematic Operation

# EXPLANATION : Arthematic Operation possible because , Here a = (4,3) is 2D and b =(3) is 1D
# so did converted (3) to (1,3) and streched to (4,3)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
# Could not Broadcast
a = np.arange(12).reshape(3,4)
b = np.arange(3)
print(a)
print(b)
print(a+b)

# EXPLANATION : Arthematic Operation not possible because , Here a = (3,4) is 2D and b =(3)
# is 1D so did converted (3) to (1,3) and streched to (3,3) but , a is not equals to b . so it got failed

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [8]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


EXPLANATION : Arthematic Operation possible because , Here a = (1,3) is 2D and b =(3,1) is
2D so did converted (1,3) to (3,3) and b(3,1) convert (1)to 3 than (3,3) . finally it equally